# Timeout for reading data in ms
USB_READ_TIMEOUT		= 10000

# Device VID & PID
#USB_VID                 = 0x16D0
#USB_PID                 = 0x09A0
USB_VID                 = 0x1209
USB_PID                 = 0x4321

# TLV Field indexes
LEN_INDEX               = 0x00
CMD_INDEX               = 0x01
DATA_INDEX              = 0x02

# Field Indexes
PREV_ADDRESS_INDEX      = 0x02
NEXT_ADDRESS_INDEX      = 0x04
NEXT_CHILD_INDEX        = 0x06
SERVICE_INDEX           = 0x08
DESC_INDEX              = 6
LOGIN_INDEX             = 37

# Sizes
NODE_SIZE					= 132
DEVICE_PASSWORD_SIZE		= 62
MINI_DEVICE_PASSWORD_SIZE	= 16
UID_REQUEST_KEY_SIZE		= 16
UID_KEY_SIZE				= 6
AES_KEY_SIZE				= 32
AES_BLOCK_SIZE				= 16

# Ack / Nack defines
CMD_HID_ACK					= 0x01
CMD_HID_NACK				= 0x00

# New Command IDs
CMD_PING                	= 0x0001
CMD_ID_RETRY				= 0x0002
CMD_ID_PLAT_INFO			= 0x0003
CMD_GET_DEVICE_STATUS		= 0x0011
CMD_GET_DEVICE_LANG			= 0x0017
CMD_GET_RANDOM_32B			= 0x0008
CMD_ID_RECONDITION_BAT      = 0x0028
CMD_ID_START_BUNDLE_UL      = 0x0029
CMD_ID_WRITE_BUNDLE_256B	= 0x002A
CMD_ID_END_BUNDLE_UL		= 0x002B
CMD_ID_AUTH_CHALLENGE		= 0x002C
CMD_ID_GET_DIAG_DATA		= 0x002D
CMD_ID_GET_DEVICE_INT_SN	= 0x0038
CMD_ID_SET_DEVICE_INT_SN	= 0x003A
CMD_ID_PREPARE_SN_FLASH		= 0x003D

# New Debug Command IDs
CMD_DBG_MESSAGE					= 0x8000
CMD_DBG_OPEN_DISP_BUFFER		= 0x8001
CMD_DBG_SEND_TO_DISP_BUFFER		= 0x8002
CMD_DBG_CLOSE_DISP_BUFFER		= 0x8003
CMD_DBG_ERASE_DATA_FLASH		= 0x8004
CMD_DBG_IS_DATA_FLASH_READY		= 0x8005
CMD_DBG_DATAFLASH_WRITE_256B	= 0x8006
CMD_DBG_REBOOT_TO_BOOTLOADER	= 0x8007
CMD_DBG_GET_ACC_32_SAMPLES		= 0x8008
CMD_DBG_FLASH_AUX_MCU			= 0x8009
CMD_DBG_GET_PLAT_INFO			= 0x800A
CMD_DBG_REINDEX_BUNDLE			= 0x800B
HID_CMD_ID_SET_OLED_PARAMS      = 0x800C
HID_CMD_ID_GET_BATTERY_STATUS   = 0x800D
HID_CMD_ID_FLASH_AUX_AND_MAIN   = 0x800E
HID_CMD_ID_GET_PLAT_TIME        = 0x800F
CMD_DBG_FLASH_PLAT_UNIQUE_DATA	= 0x8010

# OLD Command IDs
CMD_EXPORT_FLASH_START  = 0x8A
CMD_EXPORT_FLASH        = 0x8B
CMD_EXPORT_FLASH_END    = 0x8C
CMD_IMPORT_FLASH_BEGIN  = 0x8D
CMD_IMPORT_FLASH        = 0x8E
CMD_IMPORT_FLASH_END    = 0x8F
CMD_EXPORT_EEPROM_START = 0x90
CMD_EXPORT_EEPROM       = 0x91
CMD_EXPORT_EEPROM_END   = 0x92
CMD_IMPORT_EEPROM_BEGIN = 0x93
CMD_IMPORT_EEPROM       = 0x94
CMD_IMPORT_EEPROM_END   = 0x95
CMD_ERASE_EEPROM        = 0x96
CMD_ERASE_FLASH         = 0x97
CMD_ERASE_SMC           = 0x98
CMD_DRAW_BITMAP         = 0x99
CMD_SET_FONT            = 0x9A
CMD_USB_KEYBOARD_PRESS  = 0x9B
CMD_STACK_FREE          = 0x9C
CMD_CLONE_SMARTCARD     = 0x9D
CMD_DEBUG               = 0xA0
CMD_VERSION             = 0xA2
CMD_CONTEXT             = 0xA3
CMD_GET_LOGIN           = 0xA4
CMD_GET_PASSWORD        = 0xA5
CMD_SET_LOGIN           = 0xA6
CMD_SET_PASSWORD        = 0xA7
CMD_CHECK_PASSWORD      = 0xA8
CMD_ADD_CONTEXT         = 0xA9
CMD_SET_BOOTLOADER_PWD  = 0xAA
CMD_JUMP_TO_BOOTLOADER  = 0xAB
CMD_GET_RANDOM_NUMBER   = 0xAC
CMD_START_MEMORYMGMT    = 0xAD
CMD_IMPORT_MEDIA_START  = 0xAE
CMD_IMPORT_MEDIA        = 0xAF
CMD_IMPORT_MEDIA_END    = 0xB0
CMD_SET_MOOLTIPASS_PARM = 0xB1
CMD_GET_MOOLTIPASS_PARM = 0xB2
CMD_RESET_CARD          = 0xB3
CMD_READ_CARD_CREDS     = 0xB4
CMD_RESERVED            = 0xB5
CMD_SET_CARD_LOGIN      = 0xB6
CMD_SET_CARD_PASS       = 0xB7
CMD_ADD_UNKNOWN_CARD    = 0xB8
CMD_MOOLTIPASS_STATUS   = 0xB9
CMD_FUNCTIONAL_TEST_RES = 0xBA
CMD_SET_DATE            = 0xBB
CMD_SET_UID             = 0xBC
CMD_GET_UID             = 0xBD
CMD_SET_DATA_SERVICE    = 0xBE
CMD_ADD_DATA_SERVICE    = 0xBF
CMD_WRITE_32B_IN_DN     = 0xC0
CMD_READ_32B_IN_DN      = 0xC1
CMD_GET_CUR_CPZ		    = 0xC2
CMD_CANCEL_REQUEST      = 0xC3
CMD_PLEASE_RETRY        = 0xC4
CMD_READ_FLASH_NODE     = 0xC5
CMD_WRITE_FLASH_NODE    = 0xC6
CMD_GET_FAVORITE        = 0xC7
CMD_SET_FAVORITE        = 0xC8
CMD_GET_STARTING_PARENT = 0xC9
CMD_SET_STARTING_PARENT = 0xCA
CMD_GET_CTRVALUE        = 0xCB
CMD_SET_CTRVALUE        = 0xCC
CMD_ADD_CARD_CPZ_CTR    = 0xCD
CMD_GET_CARD_CPZ_CTR    = 0xCE
CMD_CARD_CPZ_CTR_PACKET = 0xCF
CMD_GET_30_FREE_SLOTS   = 0xD0
CMD_GET_DN_START_PARENT = 0xD1
CMD_SET_DN_START_PARENT = 0xD2
CMD_END_MEMORYMGMT      = 0xD3
CMD_SET_USER_CHANGE_NB 	= 0xD4
CMD_GET_DESCRIPTION		= 0xD5
CMD_GET_USER_CHANGE_NB	= 0xD6
CMD_GET_FREE_NB_USR_SLT	= 0xD7
CMD_SET_DESCRIPTION		= 0xD8
CMD_LOCK_DEVICE			= 0xD9
CMD_GET_MINI_SERIAL		= 0xDA
CMD_UNLOCK_WITH_PIN		= 0xDB